# Forward propagation y análisis de representaciones intermedias

In [1]:
import numpy as np

In [2]:
def sigmoid(X):
    return 1/(1+np.exp(-X))

# Red 1
![Red_1.png](Graphs/Red_1.png)

In [3]:
class RedNeuronal_1:
    def __init__(self):
        # 1 fila por neurona , 1 columna por variable de entrada
        self.Wc1 = np.array([
            [5,2],
            [7,-3]
        ])

        # 1 elemento para cada neurona intermedia
        self.Wc2  = np.array([7,5])

    def forward_propagation(self,X):
        print(X.shape)
        print(self.Wc1.T.shape)
        A = sigmoid(np.matmul(X,self.Wc1.T)) # 1 fila por observacion, 1 columna por representacion intermedia 
        #print(A)
        #print(A.shape)
        y_aprox = sigmoid(np.matmul(A,self.Wc2)) # 1 fila por observacion,  1 unica salida 
        #print(y_aprox.shape)
        return y_aprox

In [4]:
# 4 observaciones, 2 variables
X = np.array([
      [1,1],
      [1,2],
      [4,5],
      [6,7],
])

In [5]:
red1 = RedNeuronal_1()
y_aprox1 = red1.forward_propagation(X)
y_aprox1

(4, 2)
(2, 2)


array([0.99999323, 0.9999764 , 0.99999386, 0.99999386])

# Red 2
![Red_2.png](Graphs/Red_2.png)

In [6]:
class RedNeuronal_2:
    def __init__(self):
        # 1 fila por neurona , 1 columna por variable de entrada
        self.cero = 0
        self.Wc1 = np.array([
            [0.1,self.cero],
            [0.2,-0.3],
            [0.4,-0.5],
            [-0.1,self.cero]
        ])

        # 1 elemento para cada neurona intermedia
        self.Wc2  = np.array([0.7,0.5,0.3,-0.1])

    def forward_propagation(self,X):
        #print(X.shape)
        #print(self.Wc1.T.shape)
        A = sigmoid(np.matmul(X,self.Wc1.T)) # 1 fila por observacion, 1 columna por representacion intermedia 
        #print(A)
        #print(A.shape)
        y_aprox = sigmoid(np.matmul(A,self.Wc2)) # 1 fila por observacion,  1 unica salida 
        #print(y_aprox.shape)
        return y_aprox

In [7]:
red2 = RedNeuronal_2()
y_aprox2 = red2.forward_propagation(X)
y_aprox2

array([0.66818777, 0.65179589, 0.65284568, 0.65384242])

# Red 3
![Red_3.png](Graphs/Red_3.png)

In [8]:
class RedNeuronal_3:
    def __init__(self):
        # 1 fila por neurona , 1 columna por variable de entrada
        self.Wc1 = np.array([
            [0.1,0.2,-0.15],
            [0.2,-0.3,0.4],
            [0.4,-0.5,0.1],
            [-0.1,0.8,0.9]
        ])

        # 1 elemento para cada neurona intermedia
        self.Wc2  = np.array([
            [0.7,0.5,0.3,-0.1],
            [0.1,0.2,-0.5,0.3]
        ])

    def forward_propagation(self,X):
        #print(X.shape)
        #print(self.Wc1.T.shape)
        A = sigmoid(np.matmul(X,self.Wc1.T)) # 1 fila por observacion, 1 columna por representacion intermedia 
        #print(A.shape)
        #print(self.Wc2.T.shape)
        y_aprox = sigmoid(np.matmul(A,self.Wc2.T)) # 1 fila por observacion,  2 unica salida 
        #print(y_aprox.shape)
        return y_aprox

In [9]:
# 4 observaciones, 3 variables
X = np.array([
      [1,1,1],
      [1,2,3],
      [4,5,6],
      [6,7,8],
])

In [10]:
red3 = RedNeuronal_3()
y_aprox3 = red3.forward_propagation(X)
y_aprox3

array([[0.67485362, 0.54196033],
       [0.67543696, 0.5675921 ],
       [0.70809885, 0.5789677 ],
       [0.72413943, 0.58370282]])