## XOR con composición

In [1]:
def operacion_XOR(x1,x2):
    _and = x1+x2-1>0
    _or = x1+x2>0
    return int(_or-_and)

In [2]:
print(operacion_XOR(0,0),operacion_XOR(0,1),operacion_XOR(1,0),operacion_XOR(1,1))

0 1 1 0


Donde comprobamos que la función definida se comporta como esperamos.

##  Perceptrones
### And y Or

Para el perceptron And definimos primero el dataset, el cual es emular la tabla de verdad para dos proposiones x1 y x2.

In [3]:
import numpy as np
import random

In [4]:
x1 = [0,1]
x2 = [0,1]
dataset_x = np.array([[a,b,1] for a in x1 for b in x2])
dataset_y_and = np.array([int(a+b-1>0) for a in x1 for b in x2])
dataset_y_or = np.array([int(a+b>0) for a in x1 for b in x2])
dataset_x,dataset_y_and,dataset_y_or

(array([[0, 0, 1],
        [0, 1, 1],
        [1, 0, 1],
        [1, 1, 1]]),
 array([0, 0, 0, 1]),
 array([0, 1, 1, 1]))

Procedemos a definir una funcion de convergencia, que nos indique cuando todos los valores del dataset sean predichos con el perceptron simple, de laforma correcta según lo esperado.

In [5]:
def Convergencia(dataset_x,dataset_y,w):
    pred = np.matmul(dataset_x,w)
    pred[pred>=0] = 1
    pred[pred<0] = 0
    val = pred == dataset_y
    return val.all()

Creamos ahora el dataset y las variables iniciales para la construcción del perceptron, en éste caso se empieza a construir el perceptron para and. Se utiliza la función "np.random.seed" para poder replicar los valores obtenidos.

In [6]:
dataset_y = dataset_y_and.copy()
P_index = np.where(dataset_y==1)
N_index = np.where(dataset_y==0)
np.random.seed(30)
w = np.random.normal(0,1,3)
epochs = 0; convergencia = False
max_epochs = 100

Construimos el ciclo que encontrará los valores que buscamos para la separación del espacio según el operador "and" o si no logra converger en cierta cantidad de epochs se detiene.

In [7]:
while epochs < max_epochs and convergencia == False:
    epochs+=1
    np.random.seed(epochs)
    random_1 = np.random.randint(4, size=1)
    x = dataset_x[random_1].reshape((3,))
    #print(random_1,np.dot(w,x))
    if random_1 in P_index[0] and np.dot(w,x)<0:
        #print("Entramos 1")
        w = w+x
    if random_1 in N_index[0] and np.dot(w,x)>=0:
        #print("Entramos 2")
        w = w-x  
    convergencia = Convergencia(dataset_x,dataset_y,w)
    if epochs % (max_epochs/10) ==0:
        print("Epoch: ",epochs, " Convergencia: ", convergencia, " pesos:", w)
        
if convergencia:
    print("Se logró la convergencia en ", epochs, " iteraciones con los pesos: ",w)
    w_and = w
else:
    print("No see logró la convergencia en ", epochs, " iteraciones, pesos finales: ",w)

Epoch:  10  Convergencia:  False  pesos: [-0.26405266  0.52790535 -1.97071094]
Se logró la convergencia en  18  iteraciones con los pesos:  [ 0.73594734  1.52790535 -1.97071094]


Repetimos lo anterior pero para la función or.

In [8]:
dataset_y = dataset_y_or.copy()
P_index = np.where(dataset_y==1)
N_index = np.where(dataset_y==0)
np.random.seed(30)
w = np.random.normal(0,1,3)
epochs = 0; convergencia = False
max_epochs = 100

In [9]:
while epochs < max_epochs and convergencia == False:
    epochs+=1
    np.random.seed(epochs)
    random_1 = np.random.randint(4, size=1)
    x = dataset_x[random_1].reshape((3,))
    #print(random_1,np.dot(w,x))
    if random_1 in P_index[0] and np.dot(w,x)<0:
        #print("Entramos 1")
        w = w+x
    if random_1 in N_index[0] and np.dot(w,x)>=0:
        #print("Entramos 2")
        w = w-x  
    convergencia = Convergencia(dataset_x,dataset_y,w)
    if epochs % (max_epochs/10) ==0:
        print("Epoch: ",epochs, " Convergencia: ", convergencia, " pesos:", w)
        
if convergencia:
    print("Se logró la convergencia en ", epochs, " iteraciones con los pesos: ",w)
    w_or = w
else:
    print("No see logró la convergencia en ", epochs, " iteraciones, pesos finales: ",w)

Epoch:  10  Convergencia:  False  pesos: [0.73594734 1.52790535 1.02928906]
Epoch:  20  Convergencia:  False  pesos: [0.73594734 1.52790535 0.02928906]
Epoch:  30  Convergencia:  False  pesos: [ 0.73594734  1.52790535 -0.97071094]
Se logró la convergencia en  33  iteraciones con los pesos:  [ 1.73594734  1.52790535 -0.97071094]


Con los perceptronoes (pesos) construidos procedemos a probar éstos con la función "xor".

In [10]:
def operacion_XOR_perceptrones(x1,x2):
    x = np.array([x1,x2,1])
    _and = np.dot(w_and,x)>0
    _or = np.dot(w_or,x)>0
    #print(type(bool(_and)),_or)
    return int(bool(_or)-bool(_and))

In [11]:
print(operacion_XOR_perceptrones(0,0),operacion_XOR_perceptrones(0,1),operacion_XOR_perceptrones(1,0),operacion_XOR_perceptrones(1,1))

0 1 1 0


Podemos comprobar que obtuvimos los valores esperados.